Improve KGDB enabled build for news68k: * include sys/kgdb.h in news68k/trap.c for missing definitions. * cast second kgdb_trap argument to (db_regs_t *). * build m68k/kgdb_machdep.c for kgdb_trap() implementation.
Same as for mvme68k, build complains about undefined reference to zs_check_kgdb
due to missing port specific zs kgdb implementation for MI zs(4) driver though.