Pull up following revision(s) (requested by mrg in ticket #84):
	external/gpl3/gcc/lib/libstdc++-v3/arch/i386/defs.mk: revision 1.27
	external/gpl3/gcc/lib/libstdc++-v3/arch/riscv32/defs.mk: revision 1.18
	external/gpl3/gcc/lib/libstdc++-v3/arch/mips64el/defs.mk: revision 1.24
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv7hf/defs.mk: revision 1.23
	share/mk/bsd.lib.mk: revision 1.420
	share/mk/bsd.lib.mk: revision 1.421
	external/gpl3/gcc/lib/libstdc++-v3/arch/hppa/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/riscv64/defs.mk: revision 1.17
	external/gpl3/gcc/lib/libstdc++-v3/arch/x86_64/defs.mk: revision 1.27
	external/gpl3/gcc/lib/libstdc++-v3/arch/m68000/defs.mk: revision 1.25
	external/gpl3/gcc/lib/libstdc++-v3/arch/mipsel/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/sparc/defs.mk: revision 1.25
	external/gpl3/gcc/lib/libstdc++-v3/arch/mipsn64eb/defs.mk: revision 1.9
	external/gpl3/gcc/lib/libstdc++-v3/arch/alpha/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/ia64/defs.mk: revision 1.22
	external/gpl3/gcc/lib/libgcc/Makefile: revision 1.6
	external/gpl3/gcc/dist/libstdc++-v3/src/c++98/istream.cc: revision 1.10
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmeb/defs.mk: revision 1.24
	external/gpl3/gcc/lib/libstdc++-v3/arch/aarch64eb/defs.mk: revision 1.12
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmhf/defs.mk: revision 1.25
	external/gpl3/gcc/lib/libstdc++-v3/Makefile: revision 1.59
	external/gpl3/gcc/dist/libstdc++-v3/src/c++98/compatibility.cc: revision 1.10
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv6hfeb/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/earm/defs.mk: revision 1.23
	tools/gcc/mknative-gcc: revision 1.122
	external/gpl3/gcc/lib/libstdc++-v3/arch/powerpc64/defs.mk: revision 1.22
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv7hfeb/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/m68k/defs.mk: revision 1.24
	external/gpl3/gcc/dist/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc: revision 1.8
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv4eb/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmhfeb/defs.mk: revision 1.23
	external/gpl3/gcc/dist/libstdc++-v3/src/c++11/compatibility-thread-c++0x.cc: revision 1.9
	external/gpl3/gcc/lib/libstdc++-v3/arch/sh3eb/defs.mk: revision 1.25
	external/gpl3/gcc/lib/libgcc/libgcc_s/Makefile: revision 1.17
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv7/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/mips64eb/defs.mk: revision 1.24
	external/gpl3/gcc/lib/libstdc++-v3/arch/mipsn64el/defs.mk: revision 1.9
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv6/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/aarch64/defs.mk: revision 1.20
	external/gpl3/gcc/lib/libstdc++-v3/arch/mipseb/defs.mk: revision 1.24
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv6eb/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv4/defs.mk: revision 1.24
	external/gpl3/gcc/lib/libstdc++-v3/Makefile: revision 1.62
	external/gpl3/gcc/lib/libstdc++-v3/Makefile: revision 1.63
	external/gpl3/gcc/lib/libstdc++-v3/Makefile: revision 1.64
	external/gpl3/gcc/lib/libstdc++-v3/arch/vax/defs.mk: revision 1.25
	external/gpl3/gcc/lib/libstdc++-v3/arch/powerpc/defs.mk: revision 1.24
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv6hf/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/sparc64/defs.mk: revision 1.24
	external/gpl3/gcc/lib/libstdc++-v3/arch/sh3el/defs.mk: revision 1.23
	external/gpl3/gcc/lib/libstdc++-v3/arch/earmv7eb/defs.mk: revision 1.23
	(all via patch)


fix sanitizer flags for private libraries in executables.

update the comment to explain why we don't do -g for normal archives,
but why we do them for private archives (they are linked into the
executables, and the debug info is in the debug file for that.)
while i still don't know why dhcpd is crashing on arm64eb for me,
at least now ASAN reports don't have missing info for the various
private libraries.

fix the libstdc++ build for GCC 14.
some parts of the libstdc++ build have different flags for different
files *only* for the shared library version of the build.  netbsd
share/mk has no current method of doing this, so introduce support
for having "CSHLIBFLAGS.$file" like we do for other options, and use
it to add -D_GLIBCXX_SHARED to *most* but not all files.
XXX: see if similar should really be applied to prior updates.

properly fix our libstdc++ build.
remove our local _GLIBCXX_COMPAT_ bits, and properly build like upstream
does, for the static vs shared libraries.
now we both aren't missing std::istream::ignore(long) or the old compat
std::condition_variable::wait(std::unique_lock<std::mutex>&) that some
of the rust binary bootstraps need.  this makes rust build again on arm64,
and (probably) fixes the same for sparc64 (that build won't finish for
a bit more...)

pullout parts of libbacktrace for libstdc++.

regen for libstdc++ libbacktrace fixes.

build the libstdc++ libbacktrace bits like libstdc++ does.
should fix ia64 issue, and makes other things not broken too.
add missing -include of the rename.h.  now it actually seems to work.

fix libgcc_s build: link it against -lgcc (!).
make sure libgcc is built before libgcc_s.
this fixes several issues i saw on arm64 and other platforms where
symbols in libgcc_s were "not found", even if present elsewhere.
this is how upstream builds libgcc_s too, eg:
   ld: /usr/lib/libgcc_s.so: undefined reference to `__aarch64_cas8_acq_rel'