- sanitizers are updated - add 'switched' column to port list - update many working ports - add a second list of cpus vs. ports that have been tested to build
remaining issues:

- eabi arm vs libgcc
- vax-gcc ICE
- ppc64-gcc ICE
- sun2 build
- ia64 libgcc
- sh3 vs. compiler_rt: udivmoddi4.c:190: undefined reference to `abort'
- x68k memswitch triggers new warnings
- sun3 bloated
- mips64* has ./usr/lib/64/libgomp.so.2 as a missing file in sets