stdarg.h: fix va_arg in lint mode for lint's strict bool mode
Since va_list does not have type 'bool', lint complained about using it
in a '?:' operator:

> error: left operand of '?' must be bool, not 'pointer' [331]