kvm_mkdb(8): Replace nonstandard SIZE_T_MAX by standard SIZE_MAX.
Should we delete this?  It was unhooked from the build in 2003 and it
no longer builds now:

/home/riastradh/netbsd/current/src/usr.sbin/kvm_mkdb/kvm_mkdb.c: In function 'main':
/home/riastradh/netbsd/current/src/usr.sbin/kvm_mkdb/kvm_mkdb.c:133:24: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  133 |                 dbname = _PATH_KVMDB;
      |                        ^
/home/riastradh/netbsd/current/src/usr.sbin/kvm_mkdb/kvm_mkdb.c:155:35: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  155 |                         nlistpath = _PATH_KSYMS;
      |                                   ^
/home/riastradh/netbsd/current/src/usr.sbin/kvm_mkdb/kvm_mkdb.c:157:35: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  157 |                         nlistpath = _PATH_UNIX;
      |                                   ^