sys/conf/lint.mk: a small step for linting the kernel
Due to the missing path, the following commands had failed:

	$ cd src/sys/arch/amd64/compile/GENERIC
	$ nbmake-amd64-lint kern_exec.ln
	nbmake: don't know how to make kern/kern_exec.c. Stop

After fixing the path, "make kern_exec.ln" fails with:

	sys/kern/kern_exec.c(65): error: syntax error '"' [249]

The affected line contains:

	__KERNEL_RCSID(0, "...");

The macro __KERNEL_RCSID expands to __asm("some strings").  Since
KERNLINTFLAGS is missing the -g, lint does not recognize __asm as
keyword and tries to parse it as an identifier instead, expecting a
variable or function declaration.