Missing files from commit for ticket #1280:
        sys/arch/x86/x86/hypervvar.h: revision 1.1
        sys/dev/hyperv/genfb_vmbus.c: revision 1.1
        sys/dev/hyperv/genfb_vmbusvar.h: revision 1.1
        sys/dev/hyperv/hvkbd.c: revision 1.1
        sys/dev/hyperv/hvkbdvar.h: revision 1.1

Added drivers for Hyper-V Synthetic Keyboard and Video device.

Avoid undefined reference to `hyperv_guid_video' without vmbus(4).

Avoid undefined reference to `hyperv_is_gen1' without hyperv(4).

Use efi_probe().